server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.112.128.33:5432/xiaan_culturalLand?serverTimezone=GMT
    username: postgres
    password: 1234



mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.xiaancultural1.demo.pojo

pageHelper:
  helperDialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



